import "./globals.css";
import { Rubik } from "next/font/google";

// components
import Navbar from "./components/loginhead";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "PUREGOLD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>{children}</body>
    </html>
  );
}
